INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Afghanistan', 'AFG', 'AF', '93', 'Kabul', 'AFN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Aland Islands', 'ALA', 'AX', '+358-18', 'Mariehamn', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Albania', 'ALB', 'AL', '355', 'Tirana', 'ALL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Algeria', 'DZA', 'DZ', '213', 'Algiers', 'DZD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('American Samoa', 'ASM', 'AS', '+1-684', 'Pago Pago', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Andorra', 'AND', 'AD', '376', 'Andorra la Vella', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Angola', 'AGO', 'AO', '244', 'Luanda', 'AOA');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Anguilla', 'AIA', 'AI', '+1-264', 'The Valley', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Antarctica', 'ATA', 'AQ', '', '', '');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Antigua And Barbuda', 'ATG', 'AG', '+1-268', 'St. John''s', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Argentina', 'ARG', 'AR', '54', 'Buenos Aires', 'ARS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Armenia', 'ARM', 'AM', '374', 'Yerevan', 'AMD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Aruba', 'ABW', 'AW', '297', 'Oranjestad', 'AWG');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Australia', 'AUS', 'AU', '61', 'Canberra', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Austria', 'AUT', 'AT', '43', 'Vienna', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Azerbaijan', 'AZE', 'AZ', '994', 'Baku', 'AZN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bahamas The', 'BHS', 'BS', '+1-242', 'Nassau', 'BSD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bahrain', 'BHR', 'BH', '973', 'Manama', 'BHD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bangladesh', 'BGD', 'BD', '880', 'Dhaka', 'BDT');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Barbados', 'BRB', 'BB', '+1-246', 'Bridgetown', 'BBD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Belarus', 'BLR', 'BY', '375', 'Minsk', 'BYR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Belgium', 'BEL', 'BE', '32', 'Brussels', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Belize', 'BLZ', 'BZ', '501', 'Belmopan', 'BZD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Benin', 'BEN', 'BJ', '229', 'Porto-Novo', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bermuda', 'BMU', 'BM', '+1-441', 'Hamilton', 'BMD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bhutan', 'BTN', 'BT', '975', 'Thimphu', 'BTN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bolivia', 'BOL', 'BO', '591', 'Sucre', 'BOB');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bosnia and Herzegovina', 'BIH', 'BA', '387', 'Sarajevo', 'BAM');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Botswana', 'BWA', 'BW', '267', 'Gaborone', 'BWP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bouvet Island', 'BVT', 'BV', '', '', 'NOK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Brazil', 'BRA', 'BR', '55', 'Brasilia', 'BRL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('British Indian Ocean Territory', 'IOT', 'IO', '246', 'Diego Garcia', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Brunei', 'BRN', 'BN', '673', 'Bandar Seri Begawan', 'BND');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Bulgaria', 'BGR', 'BG', '359', 'Sofia', 'BGN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Burkina Faso', 'BFA', 'BF', '226', 'Ouagadougou', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Burundi', 'BDI', 'BI', '257', 'Bujumbura', 'BIF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cambodia', 'KHM', 'KH', '855', 'Phnom Penh', 'KHR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cameroon', 'CMR', 'CM', '237', 'Yaounde', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Canada', 'CAN', 'CA', '1', 'Ottawa', 'CAD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cape Verde', 'CPV', 'CV', '238', 'Praia', 'CVE');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cayman Islands', 'CYM', 'KY', '+1-345', 'George Town', 'KYD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Central African Republic', 'CAF', 'CF', '236', 'Bangui', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Chad', 'TCD', 'TD', '235', 'N''Djamena', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Chile', 'CHL', 'CL', '56', 'Santiago', 'CLP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('China', 'CHN', 'CN', '86', 'Beijing', 'CNY');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Christmas Island', 'CXR', 'CX', '61', 'Flying Fish Cove', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cocos (Keeling) Islands', 'CCK', 'CC', '61', 'West Island', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Colombia', 'COL', 'CO', '57', 'Bogota', 'COP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Comoros', 'COM', 'KM', '269', 'Moroni', 'KMF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Congo', 'COG', 'CG', '242', 'Brazzaville', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Congo The Democratic Republic Of The', 'COD', 'CD', '243', 'Kinshasa', 'CDF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cook Islands', 'COK', 'CK', '682', 'Avarua', 'NZD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Costa Rica', 'CRI', 'CR', '506', 'San Jose', 'CRC');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cote D''Ivoire (Ivory Coast)', 'CIV', 'CI', '225', 'Yamoussoukro', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Croatia (Hrvatska)', 'HRV', 'HR', '385', 'Zagreb', 'HRK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cuba', 'CUB', 'CU', '53', 'Havana', 'CUP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Cyprus', 'CYP', 'CY', '357', 'Nicosia', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Czech Republic', 'CZE', 'CZ', '420', 'Prague', 'CZK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Denmark', 'DNK', 'DK', '45', 'Copenhagen', 'DKK' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Djibouti', 'DJI', 'DJ', '253', 'Djibouti', 'DJF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Dominica', 'DMA', 'DM', '+1-767', 'Roseau', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Dominican Republic', 'DOM', 'DO', '+1-809 and 1-829', 'Santo Domingo', 'DOP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('East Timor', 'TLS', 'TL', '670', 'Dili', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Ecuador', 'ECU', 'EC', '593', 'Quito', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Egypt', 'EGY', 'EG', '20', 'Cairo', 'EGP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('El Salvador', 'SLV', 'SV', '503', 'San Salvador', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Equatorial Guinea', 'GNQ', 'GQ', '240', 'Malabo', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Eritrea', 'ERI', 'ER', '291', 'Asmara', 'ERN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Estonia', 'EST', 'EE', '372', 'Tallinn', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Ethiopia', 'ETH', 'ET', '251', 'Addis Ababa', 'ETB');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Falkland Islands', 'FLK', 'FK', '500', 'Stanley', 'FKP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Faroe Islands', 'FRO', 'FO', '298', 'Torshavn', 'DKK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Fiji Islands', 'FJI', 'FJ', '679', 'Suva', 'FJD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Finland', 'FIN', 'FI', '358', 'Helsinki', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('France', 'FRA', 'FR', '33', 'Paris', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('French Guiana', 'GUF', 'GF', '594', 'Cayenne', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('French Polynesia', 'PYF', 'PF', '689', 'Papeete', 'XPF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('French Southern Territories', 'ATF', 'TF', '', 'Port-aux-Francais', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Gabon', 'GAB', 'GA', '241', 'Libreville', 'XAF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Gambia The', 'GMB', 'GM', '220', 'Banjul', 'GMD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Georgia', 'GEO', 'GE', '995', 'Tbilisi', 'GEL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Germany', 'DEU', 'DE', '49', 'Berlin', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Ghana', 'GHA', 'GH', '233', 'Accra', 'GHS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Gibraltar', 'GIB', 'GI', '350', 'Gibraltar', 'GIP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Greece', 'GRC', 'GR', '30', 'Athens', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Greenland', 'GRL', 'GL', '299', 'Nuuk', 'DKK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Grenada', 'GRD', 'GD', '+1-473', 'St. George''s', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guadeloupe', 'GLP', 'GP', '590', 'Basse-Terre', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guam', 'GUM', 'GU', '+1-671', 'Hagatna', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guatemala', 'GTM', 'GT', '502', 'Guatemala City', 'GTQ');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guernsey and Alderney', 'GGY', 'GG', '+44-1481', 'St Peter Port', 'GBP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guinea', 'GIN', 'GN', '224', 'Conakry', 'GNF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guinea-Bissau', 'GNB', 'GW', '245', 'Bissau', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Guyana', 'GUY', 'GY', '592', 'Georgetown', 'GYD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Haiti', 'HTI', 'HT', '509', 'Port-au-Prince', 'HTG');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Heard and McDonald Islands', 'HMD', 'HM', ' ', '', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Honduras', 'HND', 'HN', '504', 'Tegucigalpa', 'HNL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Hong Kong S.A.R.', 'HKG', 'HK', '852', 'Hong Kong','HKD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Hungary', 'HUN', 'HU', '36', 'Budapest', 'HUF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Iceland', 'ISL', 'IS', '354', 'Reykjavik', 'ISK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('India', 'IND', 'IN', '91', 'New Delhi', 'INR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Indonesia', 'IDN', 'ID', '62', 'Jakarta', 'IDR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Iran', 'IRN', 'IR', '98', 'Tehran', 'IRR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Iraq', 'IRQ', 'IQ', '964', 'Baghdad', 'IQD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Ireland', 'IRL', 'IE', '353', 'Dublin', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Israel', 'ISR', 'IL', '972', 'Jerusalem', 'ILS' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Italy', 'ITA', 'IT', '39', 'Rome', 'EUR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Jamaica', 'JAM', 'JM', '+1-876', 'Kingston', 'JMD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Japan', 'JPN', 'JP', '81', 'Tokyo', 'JPY' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Jersey', 'JEY', 'JE', '+44-1534', 'Saint Helier', 'GBP' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Jordan', 'JOR', 'JO', '962', 'Amman', 'JOD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Kazakhstan', 'KAZ', 'KZ', '7', 'Astana', 'KZT'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Kenya', 'KEN', 'KE', '254', 'Nairobi', 'KES' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Kiribati', 'KIR', 'KI', '686', 'Tarawa', 'AUD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Korea North', 'PRK', 'KP', '850', 'Pyongyang', 'KPW' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Korea South', 'KOR', 'KR', '82', 'Seoul', 'KRW' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Kuwait', 'KWT', 'KW', '965', 'Kuwait City', 'KWD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Kyrgyzstan', 'KGZ', 'KG', '996', 'Bishkek', 'KGS' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Laos', 'LAO', 'LA', '856', 'Vientiane', 'LAK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Latvia', 'LVA', 'LV', '371', 'Riga', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Lebanon', 'LBN', 'LB', '961', 'Beirut', 'LBP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Lesotho', 'LSO', 'LS', '266', 'Maseru', 'LSL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Liberia', 'LBR', 'LR', '231', 'Monrovia', 'LRD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Libya', 'LBY', 'LY', '218', 'Tripolis', 'LYD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Liechtenstein', 'LIE', 'LI', '423', 'Vaduz', 'CHF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Lithuania', 'LTU', 'LT', '370', 'Vilnius', 'LTL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Luxembourg', 'LUX', 'LU', '352', 'Luxembourg', 'EUR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Macau S.A.R.', 'MAC', 'MO', '853', 'Macao', 'MOP' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Macedonia', 'MKD', 'MK', '389', 'Skopje', 'MKD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Madagascar', 'MDG', 'MG', '261', 'Antananarivo', 'MGA'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Malawi', 'MWI', 'MW', '265', 'Lilongwe', 'MWK'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Malaysia', 'MYS', 'MY', '60', 'Kuala Lumpur', 'MYR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Maldives', 'MDV', 'MV', '960', 'Male', 'MVR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mali', 'MLI', 'ML', '223', 'Bamako', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Malta', 'MLT', 'MT', '356', 'Valletta', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Man (Isle of)', 'IMN', 'IM', '+44-1624', 'Douglas, Isle of Man' ,'IMP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Marshall Islands', 'MHL', 'MH', '692', 'Majuro', 'USD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Martinique', 'MTQ', 'MQ', '596', 'Fort-de-France', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mauritania', 'MRT', 'MR', '222', 'Nouakchott', 'MRO' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mauritius', 'MUS', 'MU', '230', 'Port Louis', 'MUR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mayotte', 'MYT', 'YT', '262', 'Mamoudzou', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mexico', 'MEX', 'MX', '52', 'Mexico City', 'MXN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Micronesia', 'FSM', 'FM', '691', 'Palikir', 'USD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Moldova', 'MDA', 'MD', '373', 'Chisinau', 'MDL' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Monaco', 'MCO', 'MC', '377', 'Monaco', 'EUR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mongolia', 'MNG', 'MN', '976', 'Ulan Bator', 'MNT');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Montenegro', 'MNE', 'ME', '382', 'Podgorica', 'EUR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Montserrat', 'MSR', 'MS', '+1-664', 'Plymouth', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Morocco', 'MAR', 'MA', '212', 'Rabat', 'MAD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Mozambique', 'MOZ', 'MZ', '258', 'Maputo', 'MZN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Myanmar', 'MMR', 'MM', '95', 'Nay Pyi Taw', 'MMK' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Namibia', 'NAM', 'NA', '264', 'Windhoek', 'NAD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Nauru', 'NRU', 'NR', '674', 'Yaren', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Nepal', 'NPL', 'NP', '977', 'Kathmandu', 'NPR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Netherlands Antilles', 'ANT', 'AN', '', '', ''  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Netherlands The', 'NLD', 'NL', '31', 'Amsterdam', 'EUR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('New Caledonia', 'NCL', 'NC', '687', 'Noumea', 'XPF'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('New Zealand', 'NZL', 'NZ', '64', 'Wellington', 'NZD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Nicaragua', 'NIC', 'NI', '505', 'Managua', 'NIO');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Niger', 'NER', 'NE', '227', 'Niamey', 'XOF'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Nigeria', 'NGA', 'NG', '234', 'Abuja', 'NGN' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Niue', 'NIU', 'NU', '683', 'Alofi', 'NZD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Norfolk Island', 'NFK', 'NF', '672', 'Kingston', 'AUD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Northern Mariana Islands', 'MNP', 'MP', '+1-670', 'Saipan', 'USD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Norway', 'NOR', 'NO', '47', 'Oslo', 'NOK' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Oman', 'OMN', 'OM', '968', 'Muscat', 'OMR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Pakistan', 'PAK', 'PK', '92', 'Islamabad', 'PKR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Palau', 'PLW', 'PW', '680', 'Melekeok', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Palestinian Territory Occupied', 'PSE', 'PS', '970', 'East Jerusalem', 'ILS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Panama', 'PAN', 'PA', '507', 'Panama City', 'PAB' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Papua new Guinea', 'PNG', 'PG', '675', 'Port Moresby', 'PGK'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Paraguay', 'PRY', 'PY', '595', 'Asuncion', 'PYG');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Peru', 'PER', 'PE', '51', 'Lima', 'PEN');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Philippines', 'PHL', 'PH', '63', 'Manila', 'PHP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Pitcairn Island', 'PCN', 'PN', '870', 'Adamstown', 'NZD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Poland', 'POL', 'PL', '48', 'Warsaw', 'PLN'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Portugal', 'PRT', 'PT', '351', 'Lisbon', 'EUR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Puerto Rico', 'PRI', 'PR', '+1-787 and 1-939', 'San Juan', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Qatar', 'QAT', 'QA', '974', 'Doha', 'QAR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Reunion', 'REU', 'RE', '262', 'Saint-Denis', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Romania', 'ROU', 'RO', '40', 'Bucharest', 'RON' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Russia', 'RUS', 'RU', '7', 'Moscow', 'RUB');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Rwanda', 'RWA', 'RW', '250', 'Kigali', 'RWF' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint Helena', 'SHN', 'SH', '290', 'Jamestown', 'SHP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint Kitts And Nevis', 'KNA', 'KN', '+1-869', 'Basseterre', 'XCD' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint Lucia', 'LCA', 'LC', '+1-758', 'Castries', 'XCD'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint Pierre and Miquelon', 'SPM', 'PM', '508', 'Saint-Pierre', 'EUR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint Vincent And The Grenadines', 'VCT', 'VC', '+1-784', 'Kingstown', 'XCD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint-Barthelemy', 'BLM', 'BL', '590', 'Gustavia', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saint-Martin (French part)', 'MAF', 'MF', '590', 'Marigot', 'EUR'  );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Samoa', 'WSM', 'WS', '685', 'Apia', 'WST' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('San Marino', 'SMR', 'SM', '378', 'San Marino', 'EUR' );
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Sao Tome and Principe', 'STP', 'ST', '239', 'Sao Tome', 'STD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Saudi Arabia', 'SAU', 'SA', '966', 'Riyadh','SAR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Senegal', 'SEN', 'SN', '221', 'Dakar', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Serbia', 'SRB', 'RS', '381', 'Belgrade', 'RSD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Seychelles', 'SYC', 'SC', '248', 'Victoria', 'SCR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Sierra Leone', 'SLE', 'SL', '232', 'Freetown', 'SLL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Singapore', 'SGP', 'SG', '65', 'Singapur', 'SGD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Slovakia', 'SVK', 'SK', '421', 'Bratislava', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Slovenia', 'SVN', 'SI', '386', 'Ljubljana', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Solomon Islands', 'SLB', 'SB', '677', 'Honiara', 'SBD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Somalia', 'SOM', 'SO', '252', 'Mogadishu', 'SOS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('South Africa', 'ZAF', 'ZA', '27', 'Pretoria', 'ZAR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('South Georgia', 'SGS', 'GS', '', 'Grytviken', 'GBP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('South Sudan', 'SSD', 'SS', '211', 'Juba', 'SSP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Spain', 'ESP', 'ES', '34', 'Madrid', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Sri Lanka', 'LKA', 'LK', '94', 'Colombo', 'LKR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Sudan', 'SDN', 'SD', '249', 'Khartoum', 'SDG');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Suriname', 'SUR', 'SR', '597', 'Paramaribo', 'SRD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Svalbard And Jan Mayen Islands', 'SJM', 'SJ', '47', 'Longyearbyen', 'NOK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Swaziland', 'SWZ', 'SZ', '268', 'Mbabane', 'SZL');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Sweden', 'SWE', 'SE', '46', 'Stockholm', 'SEK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Switzerland', 'CHE', 'CH', '41', 'Berne', 'CHF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Syria', 'SYR', 'SY', '963', 'Damascus', 'SYP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Taiwan', 'TWN', 'TW', '886', 'Taipei', 'TWD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tajikistan', 'TJK', 'TJ', '992', 'Dushanbe', 'TJS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tanzania', 'TZA', 'TZ', '255', 'Dodoma', 'TZS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Thailand', 'THA', 'TH', '66', 'Bangkok', 'THB');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Togo', 'TGO', 'TG', '228', 'Lome', 'XOF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tokelau', 'TKL', 'TK', '690', '', 'NZD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tonga', 'TON', 'TO', '676', 'Nuku''alofa', 'TOP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Trinidad And Tobago', 'TTO', 'TT', '+1-868', 'Port of Spain', 'TTD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tunisia', 'TUN', 'TN', '216', 'Tunis', 'TND');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Turkey', 'TUR', 'TR', '90', 'Ankara', 'TRY');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Turkmenistan', 'TKM', 'TM', '993', 'Ashgabat', 'TMT');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Turks And Caicos Islands', 'TCA', 'TC', '+1-649', 'Cockburn Town', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Tuvalu', 'TUV', 'TV', '688', 'Funafuti', 'AUD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Uganda', 'UGA', 'UG', '256', 'Kampala', 'UGX');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Ukraine', 'UKR', 'UA', '380', 'Kiev', 'UAH');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('United Arab Emirates', 'ARE', 'AE', '971', 'Abu Dhabi', 'AED');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('United Kingdom', 'GBR', 'GB', '44', 'London', 'GBP');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('United States', 'USA', 'US', '1', 'Washington', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('United States Minor Outlying Islands', 'UMI', 'UM', '1', '', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Uruguay', 'URY', 'UY', '598', 'Montevideo', 'UYU');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Uzbekistan', 'UZB', 'UZ', '998', 'Tashkent', 'UZS');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Vanuatu', 'VUT', 'VU', '678', 'Port Vila', 'VUV');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Vatican City State (Holy See)', 'VAT', 'VA', '379', 'Vatican City', 'EUR');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Venezuela', 'VEN', 'VE', '58', 'Caracas', 'VEF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Vietnam', 'VNM', 'VN', '84', 'Hanoi', 'VND');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Virgin Islands (British)', 'VGB', 'VG', '+1-284', 'Road Town', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Virgin Islands (US)', 'VIR', 'VI', '+1-340', 'Charlotte Amalie', 'USD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Wallis And Futuna Islands', 'WLF', 'WF', '681', 'Mata Utu', 'XPF');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Western Sahara', 'ESH', 'EH', '212', 'El-Aaiun', 'MAD');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Yemen', 'YEM', 'YE', '967', 'Sanaa', 'YER');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Zambia', 'ZMB', 'ZM', '260', 'Lusaka', 'ZMK');
INSERT INTO tb_countries (name, iso3, iso2, phone_code, capital, currency) VALUES ('Zimbabwe', 'ZWE', 'ZW', '263', 'Harare', 'ZWL');